// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: dotenv.get(
      'WEB_API_KEY',
      fallback: 'AIzaSyD33wZDnt-wK1LsKtFVndZXHPtLxsxWd-k',
    ),
    appId: '1:5926014553:web:44f2fe2b35e1996d1e2b48',
    messagingSenderId: '5926014553',
    projectId: 'restaurant-project-52dfc',
    authDomain: 'restaurant-project-52dfc.firebaseapp.com',
    storageBucket: 'restaurant-project-52dfc.firebasestorage.app',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.get(
      'ANDROID_API_KEY',
      fallback: 'AIzaSyAsyLy7Sxmcd1DqXLLpoZABTIc_X7VWL94',
    ),
    appId: '1:5926014553:android:1f48de177891a6ea1e2b48',
    messagingSenderId: '5926014553',
    projectId: 'restaurant-project-52dfc',
    storageBucket: 'restaurant-project-52dfc.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: dotenv.get(
      'IOS_API_KEY',
      fallback: 'AIzaSyB_NSF6Bim20VNILpCejXZpZoWqxfj4uYo',
    ),
    appId: '1:5926014553:ios:3dba3ada346591431e2b48',
    messagingSenderId: '5926014553',
    projectId: 'restaurant-project-52dfc',
    storageBucket: 'restaurant-project-52dfc.firebasestorage.app',
    iosClientId:
        '5926014553-j5i91nj9tbqmll6un3qimu43rv8vjsug.apps.googleusercontent.com',
    iosBundleId: 'com.example.restaurantMobileApp',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: dotenv.get(
      'IOS_API_KEY',
      fallback: 'AIzaSyB_NSF6Bim20VNILpCejXZpZoWqxfj4uYo',
    ),
    appId: '1:5926014553:ios:3dba3ada346591431e2b48',
    messagingSenderId: '5926014553',
    projectId: 'restaurant-project-52dfc',
    storageBucket: 'restaurant-project-52dfc.firebasestorage.app',
    iosClientId:
        '5926014553-j5i91nj9tbqmll6un3qimu43rv8vjsug.apps.googleusercontent.com',
    iosBundleId: 'com.example.restaurantMobileApp',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: dotenv.get(
      'WINDOWS_API_KEY',
      fallback: 'AIzaSyD33wZDnt-wK1LsKtFVndZXHPtLxsxWd-k',
    ),
    appId: '1:5926014553:web:42f4fb62fc8c7abc1e2b48',
    messagingSenderId: '5926014553',
    projectId: 'restaurant-project-52dfc',
    authDomain: 'restaurant-project-52dfc.firebaseapp.com',
    storageBucket: 'restaurant-project-52dfc.firebasestorage.app',
  );
}
